format_version: 3
pipelines:
  build_and_publish_image_hellok8s:
    group: hello-k8s-app
    label_template: ${COUNT}
    lock_behavior: none
    display_order: 1
    environment_variables:
      DOCKERHUB_USERNAME: chuazj
    materials:
      git:
        git: https://github.com/Chuazj/hello-kubernetes.git
        shallow_clone: false
        auto_update: true
        branch: master
    stages:
    - build_and_publish_image:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          build_image:
            timeout: 0
            elastic_profile_id: demo-app
            artifacts:
            - external:
                id: hello-kubernetes
                store_id: dockerhub
                configuration:
                  options:
                    Image: ${DOCKERHUB_USERNAME}/hello-kubernetes
                    Tag: ${GO_PIPELINE_LABEL}
            tasks:
            - exec:
                arguments:
                - -c
                - docker build -t $DOCKERHUB_USERNAME/hello-kubernetes:$GO_PIPELINE_LABEL . -f Dockerfile
                command: /bin/bash
                run_if: passed
