format_version: 3
pipelines:
  build_and_publish_image_hellok8s:
    group: hello-k8s-app
    label_template: ${COUNT}
    lock_behavior: unlockWhenFinished
    display_order: 1
    environment_variables:
      DOCKERHUB_USERNAME: chuazj
    materials:
      git:
        git: https://github.com/Chuazj/hello-kubernetes.git
        shallow_clone: true
        auto_update: true
        branch: master
    stages:
    - build_and_publish_image:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
        jobs:
          build_image:
            timeout: 0
            elastic_profile_id: demo-app
            artifacts:
            - external:
                id: hello-kubernetes
                store_id: dockerhub
                configuration:
                  options:
                    Image: ${DOCKERHUB_USERNAME}/hello-kubernetes
                    Tag: ${GO_PIPELINE_LABEL}
            tasks:
            - exec:
                arguments:
                - -c
                - docker build --no-cache --build-arg IMAGE_VERSION="1.8" --build-arg IMAGE_CREATE_DATE="`date -u +"%Y-%m-%dT%H:%M:%SZ"`" --build-arg IMAGE_SOURCE_REVISION="`git rev-parse HEAD`" -f Dockerfile -t "hello-kubernetes:1.8" app
                command: /bin/bash
                run_if: passed
