format_version: 3
pipelines:
  deploy_to_cluster:
    group: hello-k8s-app
    label_template: ${COUNT}
    lock_behavior: none
    display_order: 3
    environment_variables:
      DOCKERHUB_USERNAME: chuazj
      NAMESPACE: gocd
    materials:
      upstream:
        pipeline:  build_and_publish_image_hellok8s
        stage: build_and_publish_image
        name: upstream_pipeline
      SourceCodeRepo:
        git: https://github.com/Chuazj/hello-kubernetes.git
        shallow_clone: false
        auto_update: true
        branch: master
        name: SourceCodeRepo
    stages:
    - deploy_to_cluster:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
        jobs:
          deploy:
            timeout: 0
            elastic_profile_id: demo-app
            tasks:
            - fetch:
                options:
                  EnvironmentVariablePrefix: ''
                  SkipImagePulling: 'true'
                artifact_id: hello-kubernetes
                pipeline: build_and_publish_image_hellok8s/build_and_publish_image
                stage: build_and_publish_image
                job: build_image
                artifact_origin: external
                run_if: passed
            - exec:
                arguments:
                command: ./app-deployment.sh
                run_if: passed
