format_version: 3
pipelines:
  deploy_to_cluster_hellok8s:
    group: hello-k8s-app
    label_template: ${COUNT}
    lock_behavior: none
    display_order: 3
    environment_variables:
      DOCKERHUB_USERNAME: chuazj
      NAMESPACE: gocd
      KUBE_TOKEN: eyJhbGciOiJSUzI1NiIsImtpZCI6IjZ0c21XR2tOMUNYalJmM1dfU0JZNjRDeDdOYmlRUDh4bUpQUXhOMnhDYU0ifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJnb2NkIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6ImdvY2QtdG9rZW4ta2x6bm4iLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoiZ29jZCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6ImU3MWI2NDk5LTM1MDktNDgxNy05MzAzLTczYTQ4MzE3YTg4YiIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpnb2NkOmdvY2QifQ.Hp3dZqZRP8wMw5rV_kQSBiO8GlEcdLSY-Xwi5CRnG8Pg5ncSvmkaWCNOZ6x8-0dPD9857-BFpXQN3RXUTvn-QkEIy2-FKxmKFsKMyBRwaRXBwTrhXY5j35C6OKtwtnT2qdwQ9nRQI_z3hAacNcUs-sGNwh4Yyb-OTmVywqAT-DaB0JBYOgiLVbcI62SB_HG5IoxD1UiGH3zS6uVelo0Zsn9quoJDF44QMrV2VtyfFepDsalqha-2qRc7lCyoLQqknu5ORTYc_WCb8Y2s0CzsMdJvQokzpnrpDtq7W4vBgQc8kTI46jhsrSbQzGbxdEjqQJwSijdQrZ1q0_gG8v1eOw 
    materials:
      upstream:
        pipeline:  build_and_publish_image_hellok8s
        stage: build_and_publish_image
        name: upstream_pipeline
      SourceCodeRepo:
        git: https://github.com/Chuazj/hello-kubernetes.git
        shallow_clone: false
        auto_update: true
        branch: master
        name: SourceCodeRepo
    stages:
    - deploy_to_cluster:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
        jobs:
          deploy:
            timeout: 0
            elastic_profile_id: demo-app
            tasks:
            - fetch:
                options:
                  EnvironmentVariablePrefix: ''
                  SkipImagePulling: 'true'
                artifact_id: hello-kubernetes
                pipeline: build_and_publish_image_hellok8s
                stage: build_and_publish_image
                job: build_image
                artifact_origin: external
                run_if: passed
            - exec:
                arguments:
                - ./app-deployment.sh
                command: /bin/bash
                run_if: passed
